// CONSULTAR CONTACTOS
http://localhost:5000/api/v1/contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbGVqYW5kcm8iLCJlbWFpbCI6ImFsZWphbmRyaXRvQGdtYWlsLmNvbSIsIkZlY2hhQ3JlYWRvIjoiMjAwMC0xMC0zMSIsImp0aSI6ImE2NzdjOTQxLThjYWMtNDUzZC1hMjk1LTBmYzE1ZmM0OTdmYyIsImV4cCI6MTYwMjA0NjgzMywiaXNzIjoiREVCU0NvbnN1bHRvcmVzLmNvbSIsImF1ZCI6IkRFQlNDb25zdWx0b3Jlcy5jb20ifQ.Y6ZkOXIsSPIhOQakEZ2J1G-rchIZXZa_-FXI6khh0aI


// ACTUALIZAR CONTACTOS

PUT http://localhost:5000/api/v1/contact/1
Content-Type: application/json

{
  "id": 1,
  "nombre": "Alejandro",
  "email": "Ale@gmail.com",
  "cedula": "15541939",
  "mensaje": "Actualización Correcta"
}

// CREAR CONTACTO

POST http://localhost:5000/api/v1/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbGVqYW5kcm8iLCJlbWFpbCI6ImFsZWphbmRyaXRvQGdtYWlsLmNvbSIsIkZlY2hhQ3JlYWRvIjoiMjAwMC0xMC0zMSIsImp0aSI6IjQxNGY4NGE5LTVlODktNDcyZC1iYjUzLWE3Yzk5NmUwYzkwNSIsImV4cCI6MTYwMTA3MjUzNCwiaXNzIjoiREVCU0NvbnN1bHRvcmVzLmNvbSIsImF1ZCI6IkRFQlNDb25zdWx0b3Jlcy5jb20ifQ.Uc47Vhq1sCqkDWeJPQkC55qSEmiuAq3MjGM2tpF2Qfc

{
  "nombre": "Ale",
  "email": "ale@gmail.com",
  "cedula": "18487193-9",
  "mensaje": "Hola"
}

// ELIMINAR UN CONTACTO

DELETE http://localhost:5000/api/v1/contact/3
